### PR TITLE
Fix premature printout of art exit status.

### PR DESCRIPTION
**Pull request by gaponenko**
Hello,
I have seen cases of art jobs reporting success with the
 
   "Art has completed and will exit with status 0."

message and then crashing in a GEANT or ROOT destructor.
There is also https://github.com/art-framework-suite/art/issues/112
that is similar (but I think not as bad as the completion was not
reported as successful anyway).

This PR attempts to fix the premature exit status printout.
The idea is to move this printout from main() into a destructor of a static
object, and try to construct that object as early as possible, so that
its destructor will only be reached if other static destructors
did not cause problems.

Andrei
NB.  Mu2e has its own copy of the main art program; I am going to submit
a similar PR there if this one is accepted.

### CODE REVIEW

**Review by knoepfel — CHANGES_REQUESTED** [review]
Thanks, Andrei--this is a reasonable solution.  Could you make a couple changes?  We suggest encapsulating all of the relevant data in the `ExitCodePrinter`.  If you can also put this in a separate file, then you can easily use it mu2e as well.  Thanks for your consideration, and thanks for the PR.

----


```c++
#ifndef art_Framework_Art_detail_ExitCodePrinter
#define art_Framework_Art_detail_ExitCodePrinter

#include "art/Framework/Art/detail/info_success.h"
#include <iostream>

namespace art::detail {
  struct ExitCodePrinter {
    int result = 0;
    std::string exec_name;
    ~ExitCodePrinter() noexcept
    {
      if (result != info_success()) {
        std::cout << exec_name << " has completed and will exit with status " << result << '.' << std::endl;
      }
    }
  };
}

#endif
```

And then usage is simple:

```c++
#include "art/Framework/Art/detail/ExitCodePrinter.h"

namespace {
  ExitCodePrinter p;
}

// other headers...

int 
main(int argc, char* argv[])
{
  p.exec_name = argv[0];
  p.result = artapp(argc, argv);
  mf::EndMessageFacility();
  return p.result;
}
```

**Comment by gaponenko** [comment]
Hi Kyle,

The encapsulation and placing ExitCodePrinter in a separate file are
good suggestions,  I will implement and push to this PR.

I noticed the introduction of exec_name in your snippet.  That would
modify the string which appears in printouts, which would in turn
break some of Mu2e grid scripts:

    if($line =~ m/^Art has completed and will exit with status 0\.$/) {
        $art_status_ok = 1;
    }

I would rather avoid such change and keep the hardcoded "Art" string
even for the mu2e executable.

Comments?
Andrei

**Comment by knoepfel** [comment]
> I noticed the introduction of exec_name in your snippet. That would modify the string which appears in printouts, which would in turn break some of Mu2e grid scripts...Comments?

Good point--keeping "Art has completed..." is prudent.

**Comment by gaponenko** [comment]
I have pushed the changes.  Note that one still has to do the info_success() check in main(): while the check in ExitStatusPrinter disables the printout, we want to return zero in such cases, not an out-of-range value https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

Note that I tested the code only in the context of Mu2e Offline; I do not have an Art build setup to test this commit.  I hope I translated mu2e to art correctly.  If not you may see a compilation error.

**Review by knoepfel — APPROVED** [review]
Thanks, Andrei!  I will make some adjustments, but the PR looks good.

**Comment by knoepfel** [comment]
@gaponenko, see https://github.com/art-framework-suite/art/commit/9e8666b8f157fc411e096121f8ef12ce541da1ea, which simplifies the usage of `ExitCodePrinter`.

**Comment by gaponenko** [comment]
Wow!  I like how you got rid of info_success() in main()!  Elegant!

Andrei

**Pull request merged**
